services:
  web:
    build: .
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - redis
    networks:
      - flask-network
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    networks:
      - flask-network

volumes:
  redis-data:

networks:
  flask-network: